version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: portfolio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: portfolio_builder
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s

  # Backend Service
  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: portfolio_backend
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: portfolio_builder
      DB_USER: portfolio_user
      DB_PASSWORD: portfolio_password
      FRONTEND_URL: http://localhost:4200
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend-node/generated:/app/generated
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/portfolio/list"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio_frontend
    environment:
      NODE_ENV: production
    ports:
      - "4200:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge
