services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: cd backend-node && npm install
    startCommand: cd backend-node && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://portfolio-frontend.onrender.com
    
  - type: web
    name: portfolio-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist/portfolio-builder
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /api/*
        destination: https://portfolio-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: portfolio-db
    databaseName: portfolio_builder
    user: portfolio_user
    plan: free
